name: FashodaMap
options:
  bundleIdPrefix: com.adrian
  minimumXcodeGenVersion: 2.30.0
targets:
  FashodaMap:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
    - Sources
    - Resources
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSLocationWhenInUseUsageDescription: The map needs your location to follow your custom daily routine.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  FashodaMapTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '17.0'
    sources:
    - Tests
    dependencies:
    - target: FashodaMap
    settings:
      CODE_SIGN_STYLE: Automatic
      GENERATE_INFOPLIST_FILE: YES
